### ISSUE TITLE
Need standalone "enable" command

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbsetuptools#11]
As we look at splitting the copy/enable steps between build/post-link, to avoid deleting files, we'll need a new high-level command:

``` shell
whatever.setup enable --prefix=...
```

Supports https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config/issues/1

**Comment by damianavila** [comment]
nbsetuptools is no longer used, so closing here.
