### ISSUE TITLE
Virtualenv ?

### ISSUE THREAD

**Issue by stuaxo** [Anaconda-Server/nbsetuptools#13]
This doesn't seem to work with virtualenv, it seems to want to write to my global python (which doesn't work as I'm not root) :/

**Comment by stuaxo** [comment]
I got this working by doing

```python setup.py install --sys_prefix $VIRTUAL_ENV``` while my virtualenv was active, it's not exactly intuitive though.

It would be nice if it could ask python its sys prefix, this seems to be an issue with jupyter too.

**Comment by damianavila** [comment]
This package functionality was superseded with the functionality upstream, in jupyter itself. Nobody is working actively on this repo. Cheers.

**Comment by stuaxo** [comment]
Thanks !

It would be great if that info was at the top of the README, or just in the description for this git repo.

**Comment by damianavila** [comment]
> It would be great if that info was at the top of the README, or just in the description for this git repo.

Added: https://github.com/Anaconda-Platform/nbsetuptools/blob/master/README.md#note

Thanks!
